name: FQ admin deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  test-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Check secret length
        env:
          SECRET: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          if [ ${#SECRET} -lt 100 ]; then
            echo "❌ Secret too short, probably invalid"
            exit 1
          else
            echo "✅ Secret length looks valid"
          fi

  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH test
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

          ssh-keyscan -H ${{ vars.REMOTE_HOST }} >> ~/.ssh/known_hosts

          ssh -o HostKeyAlgorithms=ssh-ed25519 \
              -i ~/.ssh/id_ed25519 \
              ${{ vars.REMOTE_USER }}@${{ vars.REMOTE_HOST }} "echo OK"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Build with Nuxt
        run: npm run build

      - name: Deploy to Server via SSH
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-avz --delete"
          SOURCE: ".output/"
          REMOTE_HOST: ${{ vars.REMOTE_HOST }}
          REMOTE_USER: ${{ vars.REMOTE_USER }}
          TARGET: "/fq-shop/admin/.output"
          EXCLUDE: "/node_modules/"

      - name: Execute post-deployment commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: c
          username: ${{ vars.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /fq-shop/admin
            git pull origin main --force"
            source ~/.nvm/nvm.sh
            ~/.nvm/versions/node/v24.12.0/bin/pm2 restart admin"
