name: FQ admin deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure SSH client and known_hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          
          ssh-keyscan -H ${{ vars.REMOTE_HOST }} >> ~/.ssh/known_hosts

          echo "Host remote_server" >> ~/.ssh/config
          echo "  HostName ${{ vars.REMOTE_HOST }}" >> ~/.ssh/config
          echo "  User ${{ vars.REMOTE_USER }}" >> ~/.ssh/config
          echo "  IdentityFile ~/.ssh/id_ed25519" >> ~/.ssh/config

          echo "  HostKeyAlgorithms +sk-ssh-ed25519@openssh.com" >> ~/.ssh/config
          chmod 600 ~/.ssh/config

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Build with Nuxt
        run: npm run build

      - name: Deploy to Server via SSH
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-avz --delete"
          SOURCE: ".output/"
          REMOTE_HOST: ${{ vars.REMOTE_HOST }}
          REMOTE_USER: ${{ vars.REMOTE_USER }}
          TARGET: "/fq-shop/admin"
          EXCLUDE: "/node_modules/"

      - name: Execute post-deployment commands
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ vars.REMOTE_HOST }}
          username: ${{ vars.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /fq-shop/admin
            git pull origin main --force"
            source ~/.nvm/nvm.sh
            ~/.nvm/versions/node/v24.12.0/bin/pm2 restart admin"
